nosana:
  description: Nosana docker in docker

global:
  image: nosana/podman:v1.0.12

jobs:
  - name: build
    environment:
      CONTAINER_HOST: tcp://localhost:8080
    commands:
      - docker build . -t alpine
